### ISSUE TITLE
Convert Navigation Website to Utilize eHydro Name (ChannelAreaIDPK)

### ISSUE THREAD

**Issue by shanksgavin** [jordan-clark/NAV#3]
Switch web queries from NCFID to ChannelAreaIDPK.  This is expected to instantly correct the navigation website by linking all uploaded data.  It also allows districts to continue populating their NCFIDs while not breaking (hiding) their survey data.

This needs to be communicated to Andrew for the download functions.

**Comment by shanksgavin** [comment]
This issue will require some substringing (I believe) unless you can work some magic then I'm for it.

**Comment by shanksgavin** [comment]
Priority Number 1!

**Comment by jordan-clark** [comment]
Completed.
