### ISSUE TITLE
Switch NCF_BETA to NCF

### ISSUE THREAD

**Issue by shanksgavin** [jordan-clark/NAV#4]

**Comment by jordan-clark** [comment]
I think I have already swapped this over. Is this the correct link?:

[*]/National_Admin/Hydro_Survey_Data/FeatureServer
[*]/National_Admin/National_Channel_Framework/FeatureServer

**Comment by shanksgavin** [comment]
You have updated the NCF on the production server.  The Hydro_Survey_Data feature service warrants a look.  That is a legacy service and may not be functional as intended with the new data structure.

**Comment by jordan-clark** [comment]
Completed.
